os: linux
dist: xenial
node_js:
  - 12
language: node_js
script:
  - yarn build
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: main
